### ISSUE TITLE
Duplicate generations when press.allowDuplicates=true

### ISSUE THREAD

**Issue by orefalo** [dirkmc/press#7] opened 2011-01-09 14:39 UTC
That's a serious one, and I am sorry I didn't pick it earlier.
# application.conf

```
press.allowDuplicates=true
```
# HTML

```
<!-- press-css: ugot/forms.css[0] --> 
<input type="text" id="" name="" value="" class="ugot" tabindex="1" /> Comments<br/> 
  <!-- press-css: ugot/forms.css[1] --> 
 <input....>
```
# CSS

the compressed CSS holds two copies of the same css file.

That's an serious issue, only one copy of the CSS file should be generate, the configuration flag press.allowDuplicate which only trigger the logic to through an exception or not.

**Comment by orefalo** [comment] 2011-01-10 03:52
From the doc, this is wrong

press.allowDuplicates
Indicates whether to allow files to be added to compression more than once.

press will throw an exception if you add the same file to compression twice, because usually it’s a mistake. In some cases it may be necessary, however, so for those specific cases you can set the allowDuplicates flag to true.
press.allowDuplicates=false

If you find me one application than needs to include a given .css twice I pay a beer! ...and I'll kick the author.  Never saw anything like that, the duplicate should be ignored without raising an exception.

-> Actually the flow should be renamed, raiseExceptionOnDuplicates

**Comment by dirkmc** [comment] 2011-01-12 19:17
Hi, sorry for the late response, Im on holidays at the moment.

I think we talked about this in another thread. The idea of Press is that **press.stylesheet** behaves just the same way as if you called Play's normal **stylesheet** tag.

If I understand correctly the behaviour you're suggesting is that 
1. **press.stylesheet** should keep track of whether the stylesheet has been output already
2. If press.stylesheet is called with the same file multiple times, only the first one should be output

The problem is that the order in which Play's templates are rendered is not necessarily the same as the order of the resulting HTML. For example if the template Fruits.html includes Orange.html, we don't know if Fruits.html will be rendered first or if Orange.html will be rendered first. Therefore the files may be output in a different order from which they are added to compression. (eg with compression disabled you might see fruits.css then oranges.css in the HTML, but with compression enabled you might see oranges.css then fruits.css in the compressed file). The idea of press is that you can turn compression on or off and there will be no difference to how the browser renders your page.

**Comment by orefalo** [comment] 2011-01-12 20:08
Yes !

and it makes complete sense to me... regardless of the order in which these scripts will be generated -> I can still enforce the order in the master play template.

bottom line, it doesn't make sence to output the same js tag or css tag in a given page, just output it once.

**Comment by orefalo** [comment] 2011-01-12 21:23
I believe that if your replace this

```
    if (fileInfos.containsKey(fileName) && !PluginConfig.allowDuplicates()) {
        throw new DuplicateFileException(fileType, fileName, tagName);
    }
```

with

```
    if (fileInfos.containsKey(fileName))
    {   if(PluginConfig.allowDuplicates())
             return "";
        else
        {
        throw new DuplicateFileException(fileType, fileName, tagName);
        }
     }
```

it should work,

same needs to apply for CSS

**Comment by dirkmc** [comment] 2011-01-13 15:45
Im not sure what you mean by "I can still enforce the order in the master play template".
What is the master play template?

An example to clarify what I´m saying:
Let´s say you have a calendar widget that gets output by a tag named calendar.html. The tag calls **press.stylesheet** to include calendar.css. Within calendar.css you have a line that looks like this: 

<pre>td.day {color: red}</pre>


You also have a weather widget in a tag named weather.html, that calls **press.stylesheet** to include weather.css. Within weather.css there is a line that looks like this:

<pre>td.day {color: blue}</pre>


You want to display the date at the top and bottom of the page, and the weather in the middle. So your templates  look like this

<pre>
 blog.html
  header.html 
    calendar.html
  body.html
    weather.html
  footer.html
    calendar.html
</pre>


If press were to only output a CSS file the first time it sees it, then when compression is **disabled** it would output calendar.css then weather.css.
When compression is **enabled**, it would depend on what order the tags are rendered. It might output calendar.css then weather.css, or it might output weather.css then calendar.css.

The point is that it´s not possible to know which it will output first, so you might get a situation where when compression is disabled the text is red and when compression is enabled the text is blue. The idea of press is that it will always behave the same whether enabled or disabled.

**Comment by orefalo** [comment] 2011-01-13 16:49
I get your point, but having a `td.day {color: red}` for two different widgets is a css design mistake to begin with.

It will most likely be

```
.calendar td.day {color: red}
.weather td.day {color: blue}
```

Any font end developer will tell you that you shouldn't rely on priority for your styles. you should rely on the Selector.

Your example is a good one, let's say you want TWO calendar widgets on the page...
So you turn on allowDuplicates=true to avoid press to raise an exception, right ?
What do you get now ? -> two references to my css/js files

it doesn't make sense. the allowDuplicate flag is useless when set to true.

I tried greenscript yesterday and he got it right, js/css are only generated once.
Which may actually be the major difference between the two modules... in which case, you may just remove all the logic around allowDuplicate.

**Comment by dirkmc** [comment] 2011-01-13 20:11
I agree that having the same style definition for two different widgets is a design mistake. That's why press must behave the same in dev (compression disabled) and production (compression enabled). Because if it doesn't you won't pick up this mistake until you deploy your app to production and all your widgets are the wrong colour :)

When you suggested the behaviour to allow duplicates it seems I misunderstood what you meant. I don't really see the harm in leaving it there but I may remove it in a future release.

Greenscript follows a different design philosophy that gives the developer more features while (in my opinion) also making it a little more difficult to debug. It sounds like it could be more appropriate for your use case.

Thanks for your comments, I'm going to close this thread.

**Comment by orefalo** [comment] 2011-01-13 21:52
Greenscript indeed solved my issues.

You shall remove the flag: it would be confusing to other users. I would also add a note that describes the differences between Press and Greenscript. It's not obvious to get the motivation behind Press from a first read. It's not only about dependency management.  If I got it right, the benefit of PRESS is to compress JS/CSS based on the order in which they are processed by Play.

Greenscript will most likely reorder the list.
 Correct ?

**Comment by dirkmc** [comment] 2011-01-14 20:03
Yes, you make good points. Thanks again

**Comment by dirkmc** [comment] 2011-01-21 18:43
I've released a new version of press that no longer has the allowDuplicates flag, and I've updated the description of the module.

**Comment by orefalo** [comment] 2011-01-21 18:59
I spoke with the greenscript author lately, Don't know what's your feeling about it, but I really think your two projects should merge. I did a side by side comparison and I think you guy should talk to one another.  just my 2c advise...

**Comment by dirkmc** [comment] 2011-01-21 19:02
Yes, the projects are very similar. The reason I wrote press in the first place was because Greenscript required setting up dependency graphs and I wanted something much simpler. I will have a look at it again.

**Comment by orefalo** [comment] 2011-01-21 19:10
The major thing it misses: it reorders script and css, while press doesn't. The author understands that there is a problem: if I don't define any dependencies.. why would the plugin reorder the fies, right ? anyways, I think you two should agree and come with a super press-greenscript plugin.

**Comment by dirkmc** [comment] 2011-01-21 21:44
Yes it would less confusing for users of play if there were only a single plugin to choose from. I'll take a look.

**Comment by orefalo** [comment] 2011-01-21 22:37
With your permission, I could open a new thread in Google groups and play the devil's advocate to have you two rework green/press

What do you think ?

**Closed as completed** 2011-01-22 02:43 UTC

**Comment by dirkmc** [comment] 2011-01-22 13:58
No that's fine, I'll contact him privately first. Later on we can open a thread in the google group.
